"""Emit the three Monthly P&L measurement queries from the shared contract, so they cannot
drift from the visuals they are supposed to represent.

  monthly_dispatch.dax   the BEFORE query: 28 measures x the 15-item 'Period View'
                         calculation group, filter context pinned. This is what the
                         pivotTable sends. It does NOT include the per-cell format-string
                         tax -- an EVALUATE never evaluates a formatStringDefinition -- so
                         the visual will always be slower than this number.
  monthly_grid.dax       the AFTER query: the Deneb dataset. 12 rows x 10 base measures.
  monthly_tieout.dax     the correctness gate: every one of the 315 cells computed twice --
                         once through the calculation group, once by deriving it from the
                         flat monthly dataset the way the Vega spec does -- and diffed.
                         Gate: BADDIFF = 0.

Run: python gen_monthly_queries.py
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE / "deneb"))
import gen_monthly_spec as G  # noqa: E402

YEAR = 2026
COLS = G.MONTHS + ["YTD", "YTG", "Full Year"]

HDR = ("// Generated by scripts/demo/gen_monthly_queries.py -- edit that, not this.\n"
       "// Filter context pinned to match the page: Year = %d, no other slicer selections.\n" % YEAR)


# ---------------------------------------------------------------- 1. dispatch (before)
def dispatch():
    measures = ",\n".join(
        f'        "{label}", [{G.MEASURE_BY_KEY[k]}]' for k, label, _ in G.ROWS)
    return f"""{HDR}// 15 calculation items x 28 measures = 420 dispatched cell evaluations.

EVALUATE
CALCULATETABLE (
    SUMMARIZECOLUMNS (
        'Period View'[Period View],
        'Period View'[Ordinal],
{measures}
    ),
    'DimDate'[Year] = {YEAR}
)
ORDER BY 'Period View'[Ordinal]
"""


# ---------------------------------------------------------------- 2. grid dataset (after)
def grid():
    measures = ",\n".join(
        f'        "{field}", [{m}]' for field, m in G.BASE_MEASURE.items())
    return f"""{HDR}// The whole grid, as far as the engine is concerned: 12 rows x 10 base measures.
// MonthOffset is aggregated, not grouped -- see docs/performance/05-case-unrenderable-matrix.md.

EVALUATE
CALCULATETABLE (
    SUMMARIZECOLUMNS (
        'DimDate'[Year],
        'DimDate'[MonthOfYear],
        "MonthOffset", MIN ( 'DimDate'[MonthOffset] ),
{measures}
    ),
    'DimDate'[Year] = {YEAR}
)
ORDER BY 'DimDate'[MonthOfYear]
"""


# ---------------------------------------------------------------- 3. tie-out
# The derived side reimplements, in DAX, exactly what the Vega spec does: build the twelve
# monthly rows, sum them into YTD / YTG / FY, then apply the row formulas. Comparing that to
# the calculation group is the semantics gate -- if DAX's blank rules and the spec's guards
# disagree anywhere, a cell moves.
DERIVED_ROWS = {
    "inc_act": ("IncAct", None, "base"),
    "inc_ly":  ("IncLY", None, "base"),
    "inc_var": ("IncAct", "IncLY", "varpct"),
    "cog_act": ("CogAct", None, "base"),
    "cog_ly":  ("CogLY", None, "base"),
    "cog_var": ("CogAct", "CogLY", "varpct"),
    "gp_act":  ("GPAct", None, "base"),
    "gp_ly":   ("GPLY", None, "base"),
    "gp_var":  ("GPAct", "GPLY", "varpct"),
    "gm_act":  ("GPAct", "IncAct", "ratio"),
    "gm_ly":   ("GPLY", "IncLY", "ratio"),
    "gm_var":  ("gm_act", "gm_ly", "sub"),
    "opx_act": ("OpxAct", None, "base"),
    "opx_ly":  ("OpxLY", None, "base"),
    "opx_var": ("OpxAct", "OpxLY", "varpct"),
    "opr_act": ("OpxAct", "IncAct", "negratio"),
    "opr_ly":  ("OpxLY", "IncLY", "negratio"),
    "opr_var": ("opr_act", "opr_ly", "sub"),
    "np_act":  ("NPAct", None, "base"),
    "np_ly":   ("NPLY", None, "base"),
    "np_var":  ("NPAct", "NPLY", "varpct"),
}
assert list(DERIVED_ROWS) == G.DATA_KEYS


def derived_expr(key, ref):
    """`ref(x)` names the column holding x on the aggregated column row."""
    a, b, kind = DERIVED_ROWS[key]
    if kind == "base":
        return ref(a)
    if kind == "varpct":
        return f"DIVIDE ( {ref(a)} - {ref(b)}, {ref(b)} )"
    if kind == "ratio":
        return f"DIVIDE ( {ref(a)}, {ref(b)} )"
    if kind == "negratio":
        return f"DIVIDE ( -1 * {ref(a)}, {ref(b)} )"
    if kind == "sub":
        return f"{ref(a)} - {ref(b)}"
    raise ValueError(kind)


def tieout():
    ind = " " * 16
    cg_rows = ",\n".join(f'{ind}"{k}", [{G.MEASURE_BY_KEY[k]}]' for k in G.DATA_KEYS)
    base_cols = ",\n".join(f'{ind}"{f}", [{m}]' for f, m in G.BASE_MEASURE.items())
    month_switch = ", ".join(f'{i + 1}, "{m}"' for i, m in enumerate(G.MONTHS))
    month_pass = ",\n".join(f'{ind}"{f}", [{f}]' for f in G.BASE_MEASURE)

    def agg_branch(label, pred):
        cols = ",\n".join(
            f'{ind}"{f}", SUMX ( FILTER ( __Months, {pred} ), [{f}] )' for f in G.BASE_MEASURE)
        return (f'            SELECTCOLUMNS (\n'
                f'                ROW ( "k", 1 ),\n'
                f'{ind}"Col", "{label}",\n{cols}\n'
                f'            )')

    # Two passes. The Vega spec chains formula transforms, so `gm_var` can read the `gm_act`
    # computed just above it; a single ADDCOLUMNS cannot -- a column is not visible to its own
    # siblings. Split on that dependency instead of pretending it is not there.
    pass1 = [k for k in G.DATA_KEYS if DERIVED_ROWS[k][2] != "sub"]
    pass2 = [k for k in G.DATA_KEYS if DERIVED_ROWS[k][2] == "sub"]
    derived1 = ",\n".join(
        f'{ind}"{k}", {derived_expr(k, lambda c: f"[{c}]")}' for k in pass1)
    derived2 = ",\n".join(
        f'{ind}"{k}", {derived_expr(k, lambda c: f"[{c}]")}' for k in pass2)

    # One comparison per cell. A pair counts as equal when both are blank, or when neither is
    # and they agree to a relative 1e-9 (the two paths sum in different orders).
    def cmp(k):
        a, b = f"[{k}]", f"__b_{k}"
        return (f'IF ( ISBLANK ( {a} ) && ISBLANK ( {b} ), 0,\n'
                f'                        IF ( ISBLANK ( {a} ) <> ISBLANK ( {b} ), 1,\n'
                f'                        IF ( ABS ( {a} - {b} ) <= 1E-9 * MAX ( 1, ABS ( {a} ) ), 0, 1 ) ) )')

    b_vars = "\n".join(
        f'                    VAR __b_{k} = MAXX ( __Row, [{k}] )' for k in G.DATA_KEYS)
    cmp_sum = "\n                      + ".join(cmp(k) for k in G.DATA_KEYS)

    return f"""{HDR}// Cell-for-cell tie-out: the calculation group vs the same numbers derived from the flat
// monthly dataset, exactly as the Vega spec derives them. Gate: BADDIFF_cells = 0.
//
// This is the query that proves the fast page is not just fast. It is deliberately slow --
// it runs the dispatch side -- so do not use it for timing.

DEFINE
    VAR __CurP =
        CALCULATE (
            MAX ( 'DimDate'[MonthOfYear] ),
            REMOVEFILTERS ( 'DimDate' ),
            'DimDate'[MonthOffset] = 0
        )

    // --- side A: through the calculation group, one row per period item ------------------
    VAR __A =
        CALCULATETABLE (
            SUMMARIZECOLUMNS (
                'Period View'[Period View],
{cg_rows}
            ),
            'DimDate'[Year] = {YEAR}
        )

    // --- side B: the flat monthly dataset, aggregated and then derived -------------------
    VAR __Months =
        CALCULATETABLE (
            SUMMARIZECOLUMNS (
                'DimDate'[MonthOfYear],
{base_cols}
            ),
            'DimDate'[Year] = {YEAR}
        )

    VAR __ColBase =
        UNION (
            SELECTCOLUMNS (
                __Months,
{ind}"Col", SWITCH ( [MonthOfYear], {month_switch} ),
{month_pass}
            ),
{agg_branch("YTD", "[MonthOfYear] <= __CurP")},
{agg_branch("YTG", "[MonthOfYear] > __CurP")},
{agg_branch("Full Year", "TRUE ( )")}
        )

    VAR __Derived1 =
        ADDCOLUMNS (
            __ColBase,
{derived1}
        )

    VAR __B =
        ADDCOLUMNS (
            __Derived1,
{derived2}
        )

    // --- diff -----------------------------------------------------------------------------
    VAR __Scored =
        ADDCOLUMNS (
            __A,
            "BadCells",
                VAR __col = 'Period View'[Period View]
                VAR __Row = FILTER ( __B, [Col] = __col )
{b_vars}
                VAR __Bad =
                    {cmp_sum}
                RETURN
                    IF ( ISEMPTY ( __Row ), {len(G.DATA_KEYS)}, __Bad )
        )

EVALUATE
ROW (
    "Columns_compared", COUNTROWS ( __A ),
    "Cells_compared", COUNTROWS ( __A ) * {len(G.DATA_KEYS)},
    "BADDIFF_cells", COALESCE ( SUMX ( __Scored, [BadCells] ), 0 ),
    "CurrentMonth", __CurP
)
"""


if __name__ == "__main__":
    for name, text in (("monthly_dispatch.dax", dispatch()),
                       ("monthly_grid.dax", grid()),
                       ("monthly_tieout.dax", tieout())):
        (HERE / name).write_text(text, encoding="utf-8")
        print(f"wrote {name}  ({len(text.splitlines())} lines)")
    print(f"\ncells compared by the tie-out: {len(G.DATA_KEYS)} rows x {len(COLS)} columns "
          f"= {len(G.DATA_KEYS) * len(COLS)}")
